#!/usr/bin/env bash
# init.sh — Starts dev servers for M1 (Shared Infrastructure).
# Generated by cyberoracle-harness initializer.
set -e

echo "▶ Starting CyberOracle dev environment (M1)..."

# Kill any existing processes on our ports
kill_port() {
  local port=$1
  if command -v lsof >/dev/null 2>&1; then
    lsof -ti:$port | xargs kill -9 2>/dev/null || true
  elif command -v netstat >/dev/null 2>&1; then
    pid=$(netstat -ano 2>/dev/null | grep ":$port " | grep LISTENING | awk '{print $5}' | head -1)
    [ -n "$pid" ] && taskkill //F //PID "$pid" 2>/dev/null || true
  fi
}

# M1, M2, M3: Web + Server
kill_port 3000; kill_port 3001
echo "▶ Starting web (port 3000) + server (port 3001)..."
pnpm dev:web &

echo "✓ Dev environment ready. Press Ctrl+C to stop all servers."
wait
