#!/usr/bin/env bash
# init.sh — Starts dev servers for M2 (Web + Server).
# Generated by cyberoracle-harness initializer for M2 Web 端 MVP.
set -e

echo "▶ Starting CyberOracle M2 dev environment (Web + Server)..."

kill_port() {
  local port=$1
  if command -v lsof >/dev/null 2>&1; then
    lsof -ti:$port | xargs kill -9 2>/dev/null || true
  elif command -v netstat >/dev/null 2>&1; then
    pid=$(netstat -ano 2>/dev/null | grep ":$port " | grep LISTENING | awk '{print $5}' | head -1)
    [ -n "$pid" ] && taskkill //F //PID "$pid" 2>/dev/null || true
  fi
}

# M2: Web (port 3000) + Server (port 3001)
kill_port 3000
kill_port 3001

echo "▶ Starting web (port 3000) + server (port 3001)..."
pnpm dev:web &

echo "✓ Dev environment ready. Press Ctrl+C to stop all servers."
wait
