packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  react: ^19.2.5
  react-dom: ^19.2.5
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  typescript: ^5.7.0
  zod: ^3.23.8
  zustand: ^4.5.2
  framer-motion: ^11.3.0
